"""
Hydra — Sovereign Multi-Headed AI Summoning CLI
"""

from hydra_cli._version import __version__
__author__ = "erastudil"

from hydra_cli.agent import (
    DEFAULT_AGENT_SYSTEM_PROMPT,
    HierarchicalScratchpad,
    HydraReplCompleter,
    SessionCheckpointer,
    run_agent_loop,
    run_interactive_agent,
    setup_readline_completer,
)
from hydra_cli.agent_runners import (
    AliceOrchestrator,
    AliceWorker,
    alice_available,
    hermes_available,
    pi_available,
    run_alice,
    run_hermes,
    run_pi,
)
from hydra_cli.auth import (
    PROVIDER_DIRECTORY,
    auth_wizard,
    execute_auth_command,
    get_auth_status,
    get_masked_input,
    mask_secret,
    open_registration_page,
    print_auth_status,
    probe_credential,
    save_credentials,
)
from hydra_cli.tool_adapter import (
    adapt_messages_for_prompt_tools,
    extract_tool_calls,
    format_tool_observation,
    format_tool_observation_message,
    inject_tool_prompt,
    is_tool_unsupported_error,
)
from hydra_cli.config import (
    IMMUTABLE_AGENT_INVARIANTS,
    build_cached_system_prompt,
)
from hydra_cli.mcp import (
    McpConcurrentDispatcher,
    McpDispatchResult,
    McpHeartbeatMonitor,
    McpLazyClient,
    McpManifestCache,
    McpNamespaceRouter,
    McpRegistryDiscoverer,
    McpSubprocessClient,
    McpTimeoutGuard,
    McpToolCall,
    compute_server_fingerprint,
    discover_mcp_configs,
    dispatch_concurrent,
    format_qualified_tool_name,
    get_default_concurrent_dispatcher,
    get_default_discoverer,
    get_default_manifest_cache,
    parse_qualified_tool_name,
    reset_concurrent_dispatcher,
    reset_discoverer,
    reset_manifest_cache,
)
from hydra_cli.mcp_registry import McpRegistry
from hydra_cli.native_tools import NativeToolRegistry
from hydra_cli.providers import complete
from hydra_cli.sandbox import (
    CommandInspector,
    EnvironmentScrubber,
    SandboxConfig,
    SandboxExecutionResult,
    SandboxRunner,
)
from hydra_cli.serve import run_server
from hydra_cli.speculative import (
    SpeculativeEngine,
    SpeculativeResult,
    speculative_complete,
)
from hydra_cli.ui import print_banner
from hydra_cli.voice import (
    AudioStreamBuffer,
    EnergyVAD,
    VADFrameResult,
    VADState,
)

__all__ = [
    "auth_wizard",
    "execute_auth_command",
    "get_auth_status",
    "save_credentials",
    "probe_credential",
    "print_auth_status",
    "get_masked_input",
    "mask_secret",
    "PROVIDER_DIRECTORY",
    "inject_tool_prompt",
    "extract_tool_calls",
    "format_tool_observation",
    "format_tool_observation_message",
    "is_tool_unsupported_error",
    "adapt_messages_for_prompt_tools",
    "complete",
    "run_server",
    "DEFAULT_AGENT_SYSTEM_PROMPT",
    "run_agent_loop",
    "run_interactive_agent",
    "HydraReplCompleter",
    "setup_readline_completer",
    "NativeToolRegistry",
    "HierarchicalScratchpad",
    "SessionCheckpointer",
    "IMMUTABLE_AGENT_INVARIANTS",
    "build_cached_system_prompt",
    "SandboxConfig",
    "CommandInspector",
    "EnvironmentScrubber",
    "SandboxExecutionResult",
    "SandboxRunner",
    "run_hermes",
    "run_pi",
    "hermes_available",
    "pi_available",
    "alice_available",
    "run_alice",
    "AliceOrchestrator",
    "AliceWorker",
    "McpSubprocessClient",
    "McpHeartbeatMonitor",
    "McpNamespaceRouter",
    "McpTimeoutGuard",
    "McpLazyClient",
    "McpRegistryDiscoverer",
    "discover_mcp_configs",
    "get_default_discoverer",
    "reset_discoverer",
    "McpManifestCache",
    "compute_server_fingerprint",
    "get_default_manifest_cache",
    "reset_manifest_cache",
    "McpConcurrentDispatcher",
    "McpDispatchResult",
    "McpToolCall",
    "dispatch_concurrent",
    "get_default_concurrent_dispatcher",
    "reset_concurrent_dispatcher",
    "parse_qualified_tool_name",
    "format_qualified_tool_name",
    "McpRegistry",
    "print_banner",
    "SpeculativeEngine",
    "SpeculativeResult",
    "speculative_complete",
    "EnergyVAD",
    "VADState",
    "VADFrameResult",
    "AudioStreamBuffer",
    "__version__",
]
