import re, os
with open('hydra_cli/agent.py', 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace('from hydra_cli.context import SessionContextLedger\nfrom hydra_cli.ui import render_prompt_box, wrap_text\n"""\nAutonomous ReAct agent execution loop with MCP tool calling, native coding tools, and multi-turn state.\nZero external dependencies.\n"""', '"""\nAutonomous ReAct agent execution loop with MCP tool calling, native coding tools, and multi-turn state.\nZero external dependencies.\n"""\nfrom hydra_cli.context import SessionContextLedger\nfrom hydra_cli.ui import render_prompt_box, wrap_text\nfrom hydra_cli._version import __version__')

new_prompt = 'DEFAULT_AGENT_SYSTEM_PROMPT = os.environ.get("HYDRA_AGENT_SYSTEM_PROMPT", (f"You are Hydra, an elite autonomous software engineering agent operating with the autonomy, precision, and multi-turn execution rigor of Cursor and Antigravity (v{__version__}).\\nYour mission is to solve coding tasks, refactorings, bug fixes, and implementations end-to-end with verifiable empirical proof.\\n\\nOPERATIONAL WORKFLOW (Autonomous ReAct Loop):\\n1. Inspect: Systematically explore the workspace before making changes. Use grep_search, find_files, list_dir, and read_file to inspect files, locate symbols, and understand existing patterns.\\n2. Plan: Formulate a minimal, deterministic plan. Identify invariants, dependencies, and potential side effects.\\n3. Implement: Apply surgical changes using edit_file or write_file. Prefer minimal, clean diffs that preserve existing code conventions and formatting.\\n4. Verify: Always run tests, type checks, or build commands using run_command to verify changes before declaring completion. Exit code 0 is passing; unverified assertions carry zero truth value.\\n\\nCONTEXT LEDGER & STEERING:\\n- The system maintains a rigorous context ledger of your execution history. Commands like /compact and /retrieve manipulate this state.\\n- The user may interrupt your execution or provide in-flight steering directives. You must immediately realign your plan to these directives.\\n\\nTOOL USAGE INSTRUCTIONS:\\n- Proactively invoke tools at every turn to inspect and modify state: read_file, edit_file, write_file, run_command, grep_search, find_files, list_dir.\\n- Never guess or hallucinate file contents or test results. Always read files before modifying them.\\n- Use edit_file for precise, scoped search-and-replace modifications with unique old_text.\\n- Use write_file for creating new files or complete rewrites.\\n- Use run_command to execute test suites, linters, and verification scripts.\\n- Drive tasks to verifiable completion. Do not halt prematurely, do not leave placeholders, stubs, or TODO comments.\\n- If an execution step fails, analyze the error output and iteratively fix the issue until all tests pass."),)'
content = re.sub(r'DEFAULT_AGENT_SYSTEM_PROMPT = os\.environ\.get\([^)]+\)', new_prompt, content, flags=re.DOTALL)

content = content.replace('"/tokens",\n        "/undo",', '"/tokens",\n        "/undo",\n        "/compact",\n        "/retrieve",')

content = content.replace('native_reg = NativeToolRegistry(\n                cwd=target_cwd,\n                subagent_depth=subagent_depth,\n                tier=resolved_tier or None,\n                alias=actual_alias,\n            )', 'native_reg = NativeToolRegistry(\n                cwd=target_cwd,\n                subagent_depth=subagent_depth,\n                tier=resolved_tier or None,\n                alias=actual_alias,\n            )\n            if mcp_reg and hasattr(mcp_reg, "ledger"):\n                pass\n            elif hasattr(native_reg, "ledger"):\n                native_reg.ledger = ledger')

content = content.replace('    messages: List[Dict[str, Any]] = [\n        {"role": "system", "content": sys_text},\n        {"role": "user", "content": prompt},\n    ]', '    messages: List[Dict[str, Any]] = [\n        {"role": "system", "content": sys_text},\n        {"role": "user", "content": prompt},\n    ]\n    if not resume_session or len(ledger.turns) == 0:\n        ledger.append_turn(role="user", content=prompt)')

t2 = '        if not tool_calls:\n            # Model emitted final answer -> statechart transition to COMPLETED'
r2 = '        if tool_calls:\n            ledger.append_turn(\n                role="assistant",\n                content=message.get("content") or "",\n                thought=message.get("reasoning_content") or message.get("thought"),\n                tool_calls=tool_calls\n            )\n\n        if not tool_calls:\n            # Model emitted final answer -> statechart transition to COMPLETED'
content = content.replace(t2, r2)

t3 = '        if steering_directive:\n            directive_msg = {\n                "role": "user",\n                "content": f"[IN-FLIGHT STEERING DIRECTIVE]: {steering_directive}",\n            }\n            messages.append(directive_msg)\n            current_turn_msgs.append(directive_msg)\n\n        turn_groups.append(current_turn_msgs)'
r3 = '        if steering_directive:\n            directive_msg = {\n                "role": "user",\n                "content": f"[IN-FLIGHT STEERING DIRECTIVE]: {steering_directive}",\n            }\n            messages.append(directive_msg)\n            current_turn_msgs.append(directive_msg)\n\n        if tool_executions:\n            ledger.append_turn(\n                role="tool",\n                content="",\n                tool_results=tool_executions\n            )\n        if steering_directive:\n            ledger.append_turn(\n                role="user",\n                content=f"[IN-FLIGHT STEERING DIRECTIVE]: {steering_directive}"\n            )\n\n        turn_groups.append(current_turn_msgs)'
content = content.replace(t3, r3)

t4 = '        if not tool_calls:\n            # Model emitted final answer -> statechart transition to COMPLETED\n            final_content = message.get("content", "") or ""\n            checkpointer.final_response = final_content\n            checkpointer.transition("COMPLETED")\n            return final_content'
r4 = '        if not tool_calls:\n            # Model emitted final answer -> statechart transition to COMPLETED\n            final_content = message.get("content", "") or ""\n            checkpointer.final_response = final_content\n            checkpointer.transition("COMPLETED")\n            ledger.append_turn(\n                role="assistant",\n                content=final_content,\n                thought=message.get("reasoning_content") or message.get("thought")\n            )\n            return final_content'
content = content.replace(t4, r4)

t5 = '    checkpointer.transition("MAX_TURNS")\n    last_content = messages[-1].get("content", "Agent loop reached maximum turns without termination.")\n    return str(last_content)'
r5 = '    checkpointer.transition("MAX_TURNS")\n    last_content = messages[-1].get("content", "Agent loop reached maximum turns without termination.")\n    ledger.append_turn(role="assistant", content=str(last_content))\n    return str(last_content)'
content = content.replace(t5, r5)

t6 = '        try:\n            line = input("> ").strip()\n\n            last_interrupt_time = 0.0'
r6 = '        try:\n            sys.stdout.write("> ")\n            sys.stdout.flush()\n            first_line = input()\n            lines = [first_line]\n            \n            if first_line.strip():\n                while True:\n                    next_line = input("... ")\n                    if not next_line.strip():\n                        active_steer_mode = True\n                        sys.stdout.write(f"\\n{c_bright}[Steering directive engaged: step-by-step confirmation active]{c_reset}\\n")\n                        sys.stdout.flush()\n                        break\n                    lines.append(next_line)\n                    \n            line = "\\n".join(lines).strip()\n            last_interrupt_time = 0.0'
content = content.replace(t6, r6)

with open('hydra_cli/agent.py', 'w', encoding='utf-8') as f: f.write(content)
print('Patch success')
