"""
Hydra Sovereign Desktop Application package.
Exposes FastAPI application, WebSocket streaming, sovereign Web Desk SPA,
background DesktopServer runner, session playback engine, multi-workspace manager,
browser storage persistence, model performance evaluator, command registry,
audio transcriber, notification hub, extension plugin system, and dynamic theme engine.
"""

from hydra_cli.desktop import (
    create_desktop_app,
    DesktopServer,
    run_desktop_app,
    get_desktop_html,
)
from desktop.session_player import (
    SessionTracePlayer,
    ActionTracer,
    create_player_from_runner,
)
from desktop.multi_workspace import (
    MultiWorkspaceManager,
    Workspace,
)
from desktop.browser_storage import (
    BrowserStorageManager,
    BrowserCookie,
)
from desktop.model_evaluator import (
    ModelPerformanceEvaluator,
    ModelBenchmarkSample,
    ModelMetricSample,
)
from desktop.command_registry import (
    CommandRegistry,
    CommandItem,
    normalize_shortcut,
)
from desktop.audio_transcriber import (
    AudioTranscriber,
    AudioBuffer,
    PTTState,
    TranscriptionResult,
    pcm_to_wav,
    calculate_pcm_rms,
    get_audio_transcriber,
    reset_audio_transcriber,
)
from desktop.notification_hub import (
    NotificationHub,
    Notification,
    NotificationItem,
    NotificationPriority,
    NotificationType,
    get_notification_hub,
    reset_notification_hub,
)
from desktop.extension_system import (
    ExtensionManager,
    BaseExtension,
    ExtensionManifest,
    ExtensionCapability,
    ExtensionLifecycleState,
    ExtensionContext,
    get_extension_manager,
    reset_extension_manager,
)
from desktop.theme_manager import (
    ThemeManager,
    ThemePalette,
    BUILTIN_PALETTES,
    calculate_contrast_ratio,
    check_wcag_compliance,
    get_theme_manager,
    reset_theme_manager,
)

from desktop.clipboard_manager import (
    SmartClipboardManager,
    ClipboardItem,
    ClipboardContentType,
    redact_sensitive_credentials,
    normalize_clipboard_tokens,
    parse_png_dimensions,
    get_clipboard_manager,
    reset_clipboard_manager,
)
from desktop.telemetry_gate import (
    SovereignTelemetryGate,
    LocalMetricRecord,
    is_telemetry_endpoint,
    get_telemetry_gate,
    reset_telemetry_gate,
)

from desktop.model_fallback_mesh import (
    ModelTier,
    ErrorCategory,
    CircuitState,
    CircuitBreaker,
    MeshNode,
    FallbackExecutionResult,
    ModelFallbackMesh,
    categorize_error,
    get_model_fallback_mesh,
    reset_model_fallback_mesh,
)
from desktop.state_snapshotter import (
    FileSnapshot,
    WorkspaceSnapshot,
    SnapshotDiff,
    WorkspaceSnapshotter,
    compute_bytes_sha256,
    compute_file_sha256,
    get_workspace_snapshotter,
    reset_workspace_snapshotter,
)

from desktop.playwright_codegen import (
    ActionType,
    RecordedAction,
    PlaywrightCodeGenerator,
    PlaywrightActionRecorder,
    get_action_recorder,
    reset_action_recorder,
)
from desktop.secret_vault import (
    EncryptedSecretRecord,
    SecretVault,
    derive_vault_key,
    encrypt_payload,
    decrypt_payload,
    get_secret_vault,
    reset_secret_vault,
)

from desktop.system_metrics_collector import (
    MetricSample,
    RingBuffer,
    SystemMetricsCollector,
    query_nvidia_vram_metrics,
    get_system_metrics_collector,
    reset_system_metrics_collector,
)
from desktop.model_quantizer_bridge import (
    QuantizationType,
    GGUF_BPW_MAP,
    OffloadStrategy,
    ModelArchitectureProfile,
    QuantizationEvaluationResult,
    ModelQuantizerBridge,
    calculate_weight_size_bytes,
    calculate_kv_cache_bytes,
    get_quantizer_bridge,
    reset_quantizer_bridge,
)

from desktop.model_context_compressor import (
    MessageRole,
    ContextMessage,
    CompressionStrategy,
    CompressionResult,
    ModelContextCompressor,
    get_context_compressor,
    reset_context_compressor,
)
from desktop.local_vector_indexer import (
    VectorDocumentChunk,
    SearchResult,
    LocalVectorIndexer,
    vector_dot,
    vector_norm,
    vector_normalize,
    cosine_similarity,
    generate_text_embedding,
    get_local_vector_indexer,
    reset_local_vector_indexer,
)

__all__ = [
    "create_desktop_app",
    "DesktopServer",
    "run_desktop_app",
    "get_desktop_html",
    "SessionTracePlayer",
    "ActionTracer",
    "create_player_from_runner",
    "MultiWorkspaceManager",
    "Workspace",
    "BrowserStorageManager",
    "BrowserCookie",
    "ModelPerformanceEvaluator",
    "ModelBenchmarkSample",
    "ModelMetricSample",
    "CommandRegistry",
    "CommandItem",
    "normalize_shortcut",
    "AudioTranscriber",
    "AudioBuffer",
    "PTTState",
    "TranscriptionResult",
    "pcm_to_wav",
    "calculate_pcm_rms",
    "get_audio_transcriber",
    "reset_audio_transcriber",
    "NotificationHub",
    "Notification",
    "NotificationItem",
    "NotificationPriority",
    "NotificationType",
    "get_notification_hub",
    "reset_notification_hub",
    "ExtensionManager",
    "BaseExtension",
    "ExtensionManifest",
    "ExtensionCapability",
    "ExtensionLifecycleState",
    "ExtensionContext",
    "get_extension_manager",
    "reset_extension_manager",
    "ThemeManager",
    "ThemePalette",
    "BUILTIN_PALETTES",
    "calculate_contrast_ratio",
    "check_wcag_compliance",
    "get_theme_manager",
    "reset_theme_manager",
    "SmartClipboardManager",
    "ClipboardItem",
    "ClipboardContentType",
    "redact_sensitive_credentials",
    "normalize_clipboard_tokens",
    "parse_png_dimensions",
    "get_clipboard_manager",
    "reset_clipboard_manager",
    "SovereignTelemetryGate",
    "LocalMetricRecord",
    "is_telemetry_endpoint",
    "get_telemetry_gate",
    "reset_telemetry_gate",
    "ModelTier",
    "ErrorCategory",
    "CircuitState",
    "CircuitBreaker",
    "MeshNode",
    "FallbackExecutionResult",
    "ModelFallbackMesh",
    "categorize_error",
    "get_model_fallback_mesh",
    "reset_model_fallback_mesh",
    "FileSnapshot",
    "WorkspaceSnapshot",
    "SnapshotDiff",
    "WorkspaceSnapshotter",
    "compute_bytes_sha256",
    "compute_file_sha256",
    "get_workspace_snapshotter",
    "reset_workspace_snapshotter",
    "ActionType",
    "RecordedAction",
    "PlaywrightCodeGenerator",
    "PlaywrightActionRecorder",
    "get_action_recorder",
    "reset_action_recorder",
    "EncryptedSecretRecord",
    "SecretVault",
    "derive_vault_key",
    "encrypt_payload",
    "decrypt_payload",
    "get_secret_vault",
    "reset_secret_vault",
    "MetricSample",
    "RingBuffer",
    "SystemMetricsCollector",
    "query_nvidia_vram_metrics",
    "get_system_metrics_collector",
    "reset_system_metrics_collector",
    "QuantizationType",
    "GGUF_BPW_MAP",
    "OffloadStrategy",
    "ModelArchitectureProfile",
    "QuantizationEvaluationResult",
    "ModelQuantizerBridge",
    "calculate_weight_size_bytes",
    "calculate_kv_cache_bytes",
    "get_quantizer_bridge",
    "reset_quantizer_bridge",
    "MessageRole",
    "ContextMessage",
    "CompressionStrategy",
    "CompressionResult",
    "ModelContextCompressor",
    "get_context_compressor",
    "reset_context_compressor",
    "VectorDocumentChunk",
    "SearchResult",
    "LocalVectorIndexer",
    "vector_dot",
    "vector_norm",
    "vector_normalize",
    "cosine_similarity",
    "generate_text_embedding",
    "get_local_vector_indexer",
    "reset_local_vector_indexer",
]
